baseURL: "https://pascalmichaillat.org/hugo-website/" 
title: Kexin Jiang Chen
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Projects
          url: projects/
          weight: 5 

params:
    description: "Kexin's personal website."
    author: Kexin Jiang Chen
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["projects"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Kexin Jiang Chen
          subtitle: "Research collaborator at Universitat Politècnica de València (UPV), part of the  Valencian Research Institute for Artificial Intelligence (VRAIN) and DMIP team. I completed my BSc in Data Science at UPV and I am currently pursuing an MSc in Artificial Intelligence, Pattern Recognition and Digital Imaging. My main research interests focus on AI evaluation and making AI systems more predictable and trustworthy."
          imageUrl: "perfil.png"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Projects
              url: projects/

    socialIcons:
        - name: Email
          url: kjiache@etsinf.upv.es
        - name: LinkedIn
          url: https://www.linkedin.com/in/kexin-jiang-chen
        - name: Google Scholar
          url: https://orcid.org/0009-0005-2492-6531
        - name: GitHub
          url: https://github.com/kexinjc

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Kexin Jiang Chen"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
